### PR TITLE
Restore GDPR compliance and privacy

### PR DESCRIPTION
**Pull request by DanWillman**

### CODE REVIEW

**Comment by DanWillman** [comment]
Fixes #1372 #1371 #1370

**Review by jedieaston — APPROVED** [review]

**Review by timcarterwex — APPROVED** [review]

**Review by GreemDev — APPROVED** [review]

**Review by VladimirTyrin — APPROVED** [review]

**Review by KarbyCZ — APPROVED** [review]
This PR is reverting commit [6057dd2](https://github.com/moq/moq/commit/6057dd207f597db2b8f9acc74f1fec9c8c0a2655). Looks good to me.

**Review by PoteRii — APPROVED** [review]

**Review by wdolek — APPROVED** [review]

**Review by mativp — APPROVED** [review]

**Review by batkaevruslan — APPROVED** [review]

**Review by ipatalas — APPROVED** [review]

**Review by Dynix71 — APPROVED** [review]

**Review by GeorgDangl — APPROVED** [review]

**Review by tom-scott — APPROVED** [review]

**Review by Xilconic — APPROVED** [review]

**Review by kamkie — APPROVED** [review]

**Review by aman-agrawal-coolblue — APPROVED** [review]

**Review by jbarczyk — APPROVED** [review]

**Review by BenjaminAbt — APPROVED** [review]

**Review by nickrandolph — APPROVED** [review]

**Review by willvelida — APPROVED** [review]

**Review by amandas-slabsys — APPROVED** [review]

**Review by wieslawsoltes — APPROVED** [review]

**Review by erri120 — APPROVED** [review]

**Review by sfinseth — APPROVED** [review]

**Review by jakoss — APPROVED** [review]

**Review by jamesmcroft — APPROVED** [review]

**Comment by kzu** [comment]
Considering merging this if the conversation about sustainability in OSS gets going with the folks who can actually do something about it: GitHub/Microsoft themselves. 

Consider adding your thoughts to https://github.com/moq/moq/issues/1374

**Review by kotx — APPROVED** [review]

**Review by bartdebever — APPROVED** [review]

**Review by Sewer56 — APPROVED** [review]

**Review by rdjong — APPROVED** [review]

**Review by shoter — APPROVED** [review]

**Review by durandt — APPROVED** [review]

**Review by wisedev-pstach — APPROVED** [review]

**Review by Atulin — APPROVED** [review]

**Review by jjjaniszewski — APPROVED** [review]

**Review by ch1seL — APPROVED** [review]

**Review by Debaerdm — APPROVED** [review]

**Comment by aradalvand** [comment]
> Considering merging this if the conversation about sustainability in OSS gets going with the folks who can actually do something about it: GitHub/Microsoft themselves.

If you're not convinced by now that this was an unambiguously bad decision that needs reversing ASAP then I don't know what to say.

Consider it damage control at this point, I'm sure people would be perfectly willing to have a discussion about the sustainability and sponsorship issues but you saying that makes it sound like you might still end up keeping this; which is frankly astounding... It would not hesitate to click on the "Merge" button if I were you.

**Review by martintmk — APPROVED** [review]

**Review by SelectiveHouse — APPROVED** [review]

**Review by deMD — APPROVED** [review]

**Review by Jverschoor — APPROVED** [review]

**Review by alex123098 — APPROVED** [review]

**Review by funkysi1701 — APPROVED** [review]

**Review by oliver-welch — APPROVED** [review]

**Review by Ovis — APPROVED** [review]

**Review by polamatvalls91 — APPROVED** [review]

**Comment by kzu** [comment]
Superseeded by https://github.com/moq/moq/pull/1375

**Comment by jakoss** [comment]
> Superseeded by #1375

Isn't #1375 only removing the reference to the project that contains the analysis? And under completely difference pretense?

**Comment by SelectiveHouse** [comment]
> Superseeded by #1375

Surely `SponsorLink.cs` should also be removed to supersede this PR?

**Comment by aradalvand** [comment]
> Superseeded by https://github.com/moq/moq/pull/1375

@kzu Not really. That PR's description literally says it addresses #1371; not #1372. How does it supersede this PR?!

**Comment by wardboumans** [comment]
Brilliant

**Comment by CalvinWilkinson** [comment]
Based on the actions that I am seeing by the project maintainers, they don't even want to discuss it.

At the very least, expose and be transparent about everything and try to plead your case.  Also, at least spend the time to have conversations with your community.  Isn't that one of the benefits of OS?

**Review by phillip-haydon — COMMENTED** [review]
:+1:

**Comment by ZXeno** [comment]
Watched this unfold for a bit, but closing this PR and saying it was "superceded" by another only removing a single project reference and doing aboslutely 0 to address the overwhelming backlash of privacy, GDPR, and security concerns... I'll now be removing this package from all of my personal and work projects, filing a report with my company's infosec team, and migrating all of our projects to an alternative.

Not the first package I've done this with, and I'm convinced this won't be the last.

Good luck in your efforts to secure funding going forward, but I suspect you're going to have to somehow rebuild your reputation first, and I see no clear or easy way to accomplish that.

**Comment by kzu** [comment]
@CalvinWilkinson perhaps you missed https://github.com/moq/moq/issues/1374. Please join the conversation.

Removing the project reference is enough to remove it from the package, which is why it superseded this PR.

I @ZXeno sad to see you go. I hope you enjoyed Moq all these years though!

**Comment by LucHeart** [comment]
This PR should be **reopened** as stated before.
**Not** "superseeded" by your other PR that only removes it because of "MacOS restore"..

Please be honest with your community around Moq, and dont try to downplay it with your PR. There is so many reasons for why so many people hate this change. One of the reasons is that people actually liked moq and used it for previous projects, both private and enterprises!

**Comment by CalvinWilkinson** [comment]
> @CalvinWilkinson perhaps you missed #1374. Please join the conversation.
> 
> Removing the project reference is enough to remove it from the package, which is why it superseded this PR.
> 
> I @ZXeno sad to see you go. I hope you enjoyed Moq all these years though!

I did not know this was going on.  Thanks.  I will take a look!!

**Comment by 0x56696B** [comment]
You know you've screwed things badly, when such a popular framework gets linked by the second on different projects as "replace with X, because of privacy issues".

Also, legitimate question: Why was such change merged without any PR approvals from any of the maintainers/contributers? 
I get why you pushed such change, but considering the scale of the library, it seems like quite a rushed decision. No comments, no reviews, no nothing. No public ones, at least

**Review by Crossedfall — APPROVED** [review]

**Comment by sjd2021** [comment]
I planned to use the `allowedVersions` attribute to block upgrades > 4.1.*, but I just realized that is only supported in packages.config, not with the `PackageReference` element in csproj files. Does anyone know of a way to ensure devs are significantly less likely to accidentally upgrade the package when using some sort of "use latest of everything" feature in their respective IDEs?

**Comment by ys-jeffn** [comment]
> 

Check out 
https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#Constraining_Upgrades_To_Allowed_Versions

It has details on how to block upgrades in csproj files as well.

**Comment by scovetta** [comment]
@sjd2021 I'm pretty sure you can use semantic versioning in csproj files:

`<PackageReference Include="Moq" Version="[4.18.2]" />`

https://learn.microsoft.com/en-us/nuget/concepts/package-versioning

**Comment by sjd2021** [comment]
@scovetta  That's how I had it set up, but the IDEs don't seem to do anything significant when someone generically clicks "upgrade packages" at the solution level. It just replaces it with 4.2.

**Comment by giddy11** [comment]
great

**Comment by mletterle** [comment]
> I planned to use the `allowedVersions` attribute to block upgrades > 4.1.*, but I just realized that is only supported in packages.config, not with the `PackageReference` element in csproj files. Does anyone know of a way to ensure devs are significantly less likely to accidentally upgrade the package when using some sort of "use latest of everything" feature in their respective IDEs?

There is no guarantee that SponsorLink "support" won't be backported to a minor (or patch!) release of a version < 4.20, this is what happens when trust is broken.

**Comment by wrexbe** [comment]
Can someone fork it, and make another nuget package?

May I suggest the name for the fork:
MOP
Mocking objects with privacy

Also here is an icon that could be used for the Repo, I license this image under Public Domain
Mop

**Comment by Matthew-Davey** [comment]
I suggest the forked project should be named `moqq` - because we're all crying with anguish, or laughter, or both.

**Comment by kzu** [comment]
Merging this is not really relevant anymore since SponsorLink is OSS and no longer shipping with the latest Moq, but nevertheless, it sends the right signal at this point to merge this in the meantime. 

@DanWillman could you merge main on your side and push again to your branch to GH will let me click the "Reopen" button here? I'm trying it now and it's not doing anything :(

**Comment by DanWillman** [comment]
I synced my fork with main, but I'm unable to re-open. Seems like it might be a maintainer that has to do that. If you or @stakx don't have the option for it, I could just open a new PR. Just let me know how you want to proceed.

**Comment by stakx** [comment]
@DanWillman, for me the _Reopen pull request_ button is also disabled. When I hover over it, a tooltip says, _"The main branch was force-pushed or recreated."_ Not sure how you would need to go about resolving this.

Would it perhaps be an option to submit these changes as a new PR with the same title, and link to this PR in the description (in order to retain the comment history)?

**Comment by DanWillman** [comment]
Yeah, that is probably for the best, I'm not quite sure how it ended up in this state, but no biggie.

**Pull request closed without merging**
